export interface IStats {
  name: string,
  totalPRs: number,
  totalPRsMerged: number,
  mergedPRsPercentage: number,
  totalReviews: number,
  totalCommits: number,
  totalIssues: number,
  totalStars: number,
  totalDiscussionsStarted: number,
  totalDiscussionsAnswered: number,
  totalFollowers: number,
  totalRepositories: number,
  contributedTo: number,
  rank: number,
}
